### PR TITLE
Add extra events to support FrSky new 2019 models with scroll wheel 

### PR DESCRIPTION
**Pull request by iphong**
Currently there is no way navigate through config menu.

### CODE REVIEW

**Comment by teckel12** [comment]
@iphong I believe this was already addressed?

**Comment by teckel12** [comment]
I'm not adding the virtual events in this release. It's noted that this will be added after the new year to allow time for people to upgrade to 2.3.

**Comment by teckel12** [comment]
@iphong Please see #344. The latest development build already supports the transmitter's controls.

**Comment by teckel12** [comment]
The commit where this is already fixed: https://github.com/iNavFlight/LuaTelemetry/commit/d13d2e2588bbe8a896984113785b3793b503292f

**Comment by johanvandyck** [comment]
Hi, any progress on this request? we are now on opentex 2.3.7 I own a 2019 model... and like to have the config menu.
I read: 18/9/19: "It's noted that this will be added after the new year to allow time for people to upgrade to 2.3."

**Comment by nm17** [comment]
@johanvandyck @iphong closing this since d13d2e2 was merged by df366c9. Theoretically it should work fine now on v1.7.3. If you still have issues, please reply to this issue.

**Pull request closed without merging**
