### PR TITLE
Using timer3 method for flight reset / script reset for Taranis and Horus

### PR DESCRIPTION
**Pull request by teckel12**

### CODE REVIEW

**Comment by wx4cb** [comment]
what does this do ?

**Comment by teckel12** [comment]
@wx4cb It takes the flight reset code that's been used on the Horus since the beginning and standardizes it for both Horus and Taranis.

### What it does
It uses timer 3 to detect when you do a flight reset, which then triggers the flight reset in the script.

### What reset flight does
Resets all timers and telemetry (and as a result of this PR, also resets Lua Telemetry). 

### When to use it
Between flights, if you want to reset the flight information (like max speed, distance, altitude, etc). Some things are more important to reset, like minimum battery voltage. It's best to do it while waiting for satellites before arming. 

### How to reset the flight
It's done through OpenTX. Long-press enter, which brings up a menu (which is different for every model). Select reset flight which will trigger Lua Telemetry to also reset the flight.

### How to tell it's working
Lua Telemetry will show the version information like it does when you first start.

### Why it uses timer 3
Well... Because OpenTX has no function to tell a lua script when the flight, timers or telemetry is reset. Much like OpenTX also doesn't send key events to lua scripts on Horus, a tricky method needs to be used to detect this. In the case of the flight reset, the code in this PR sets timer 3 in a certain way and then monitors it. When the flight is reset, Lua Telemetry detects this and initiates the reset.

### Wait, what if I reset just timer 3?
Don't do that. It will tell Lua Telemetry to reset the flight but not the transmitter, so it won't fully reset the flight.  Best to avoid resetting timer 3 alone.

### Why not add the function to OpenTX and end this nonsense? 
Much like Horus key events, it's been requested for years but never gets any traction to be added. I guess there's more important things to add.

### OMG! I'm using timer 3 for something really important! Will this jack my sh1t up?
Yup. But seriously, who really uses timer 3 that can't live without it?

**Comment by teckel12** [comment]
Incorporated in development branch.

**Comment by wx4cb** [comment]
oh i see.. that's cool... yea i only use timer 1 so i'm good 😆

**Comment by teckel12** [comment]
No one uses timer 3, no one.

**Pull request closed without merging**
