### PR TITLE
French support

### PR DESCRIPTION
**Pull request by d00bld0ze**
- Add 33 french .wav files 
&  
- lang_fr.lua

### CODE REVIEW

**Comment by teckel12** [comment]
@d00bld0ze No problem, I've just been really busy the last couple weeks with work and a marathon. I plan on getting to this during this week.

**Comment by d00bld0ze** [comment]
Oops sorry, I was thinking of making my changes in my fork. I did not read the documentation of Github well

Anyway, I tested and completed my changes and everything seems to work perfectly.
@teckel12 You created an excellent code, thanks for your work & sorry for my github handling error (please delete my modified README.md & gitignore)

**Comment by teckel12** [comment]
@d00bld0ze No problem, I hope to get to this tomorrow. I'll probably just create a new branch to clean things up.

**Comment by teckel12** [comment]
@d00bld0ze Closing this PR due to merge conflict and duplication of #206

**Pull request closed without merging**
