### PR TITLE
Add Jumper T12 compatibility and reduce support file path length

### PR DESCRIPTION
**Pull request by aviphysics**
Summary added config menu support for Jumper T12 and moved support files out of Telemetry folder, which reduces audio path length to acceptable level.

iNav.lua Line 511 added catch for event == EVT_DOWN_LONG, so that Jumper T12 can enter menu

menu.lua Line 121 changed EVT_ENTER_BREAK to EVT_ENTER_FIRST, Makes the interface feel snappier.
menu.lua Line 133 changed EVT_ENTER_BREAK to EVT_ENTER_FIRST, Makes the interface feel snappier.

menu.lua Line 127 added catches for EVT_MINUS_FIRST and event == EVT_DOWN_FIRST, so that menu will respond to short presses
menu.lua Line 133 added catches for EVT_MINUS_FIRST and event == EVT_DOWN_FIRST, so that menu will respond to short presses

menu.lua Line 130 added catches for EVT_PLUS_FIRST and event == EVT_UP_FIRST, so that menu will respond to short presses
menu.lua Line 155 added catches for EVT_PLUS_FIRST and event == EVT_UP_FIRST, so that menu will respond to short presses

### CODE REVIEW

**Comment by kasatka60** [comment]
downloaded the file and display a syntax error

**Comment by aviphysics** [comment]
At the time I submitted, I may not have realized that I needed to build the luac files and put them in the distribution folder.

Also, the inav folder needs to be moved outside of the telemetry folder.

Also, I later found out that the down key long press is also used for switching telemetry screens.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by kasatka60** [comment]
How to build? I didn't find instructions.

**Comment by aviphysics** [comment]
The script is setup to look directly for the luac files, if it is running on a real transmitter.

If it is running in the OpenTX simulator, it will look for and build the luac files.

I am sorry, I am not really able to explain it very well, without knowing exactly what you already know how to do. It is not difficult, but is non trivial to explain in text.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by kasatka60** [comment]
Many thanks. I'll try it in an open simulator.

**Comment by kasatka60** [comment]
Build, works. Thanks.
https://yadi.sk/d/yMzA1EA6blM2EQ

**Comment by teckel12** [comment]
@aviphysics Is there a requirement that the path length is shortened?  Traditionally, `/SCRIPTS/TELEMETRY/` was the correct path.  Is something broken by using this path?

**Pull request closed without merging**
