### PR TITLE
Update lang_de.lua

### PR DESCRIPTION
**Pull request by Peschi90**
shorten some words.

### CODE REVIEW

**Comment by teckel12** [comment]
Looks good!

**Comment by Peschi90** [comment]
I replace the Ö and Ü charakters. they cant be displayed with Lua i think

**Comment by teckel12** [comment]
@Peschi90 What about the `ä` in `Kapazität`?  I don't show that rendering correctly either, but I'm running in the Companion which is hard-coded English.

**Comment by Peschi90** [comment]
F*** I missed that... That has to be an ae too

**Comment by teckel12** [comment]
I'll take care of it.

**Pull request merged**
