### PR TITLE
v1.7.3

### LINKED ISSUE #338: Support the NV-14 Nirvana (supported by latest OFFICIAL Flysky build v2.1.7 from June 3rd)
I tried using your script on the Nirvana NV-14 with a Lua script enabled Firmware (Betaflight scripts do work) and it says "Opentx 2.2+ required" when running the script although it is a 2.2 version. The widget just says "Disabled".
Would be happy to help with trying the builds.

### LINKED ISSUE #344: Taranis X9D Plus 2019 Edition
Anyone have a 2019 version of the Taranis X9D Plus (the one with ACCESS) and can verify it works with Lua Telemetry?  I can't see why not, if anything it will run faster and allow multiple Lua scripts to run without memory issues (thanks FrSky!)

### LINKED ISSUE #347: Possible OpenTX 2.3 Issues?
Opentx 2.3 is not yet released, but at least one user has mentioned a problem with telemetry values not being received. Sounds like a possible OpenTX 2.3 bug if telemetry values are not getting to Lua Telemetry.

### PR DESCRIPTION
**Pull request by teckel12**
- Adds support for FLYSKY Nirvana NV-16 transmitter
- Adds support for X9D+ 2019 edition
- Small adjustment for OpenTX 2.3 compatibility
- Refactored many things for faster speed and reducing memory used
- Crossfire: Satellite count sanity check

Fixes: #344 
Closes: #338 
Fixes: #347

### CODE REVIEW

**Comment by MrD-RC** [comment]
Would it be possible to release 1.7.3? It has been open for over a year and was last modified in May. There are fixes in this that would allow people with certain transmitters to use the script, who currently can’t. Surely after a 5 month gap in development, it can be merged and anything else rolled in to 1.7.4 or 1.8?

**Comment by Pairan** [comment]
Looks kind'a dead currently ... @teckel12  ... what's Up? ... using the telemetry with Li-Ion is a PIA :) V1.7.3 could solve this actually !

**Comment by teckel12** [comment]
@MrD-RC @Pairan Keep in mind that you can always run the development branch by using the following instructions:

https://github.com/iNavFlight/LuaTelemetry/wiki/Upgrade-to-Development-Build

**Comment by MrD-RC** [comment]
If it were to make and test something, then yes, I’d agree. But in this instance there are plenty of useful fixes and a lull in development. A release would make much more sense to get those fixes out to everyone.

**Comment by teckel12** [comment]
@MrD-RC You are correct, but there's been issues in releasing a new version so unfortunately that hasn't happened.

**Pull request merged**
